language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hello-mongo:latest -f ./tasksapp/server/Dockerfile.mongo ./tasksapp/server
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  # - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front

script:
  - docker run --name my-mongo -d -v /tmp/mongodb:/data/db -p 27017:27017 hello-mongo
  - docker run --link my-mongo:mongo -e CI=true -e MONGODB_URL=mongodb://mongo:27017/task-manager-api -e PORT=8080 -e SENDGRID_API_KEY="$SENDGRID_API_KEY" -e JWT_SECRET="$JWT_SECRET" -e GEOCODER_PROVIDER=here -e GEOCODER_APP_ID="$GEOCODER_APP_ID" -e GEOCODER_API_KEY="$GEOCODER_KEY" yonatanaiz/server npm run docker-test
  # - docker run -e CI=true yonatanaiz/client npm run test

after_success:
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  # - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front
