language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front

script:
  - docker run --name mongo -d mongo
  - docker run -e CI=true yonatanaiz/server --rm mongo mongo --host mongo npm run docker-test
  - docker run -e CI=true yonatanaiz/client npm run test

after_success:
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front
