language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front

script:
  - docker run -e CI=true yonatanaiz/server npm run test
  - docker run -e CI=true yonatanaiz/client npm run test

