language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hello-mongo:latest -f ./tasksapp/server/Dockerfile.mongo ./tasksapp/server
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front

script:
  - docker run --name my-mongo -d -v /tmp/mongodb:/data/db -p 27017:27017 hello-mongo
  - docker run -e CI=true --link my-mongo:mongo yonatanaiz/server npm run docker-test
  - docker run -e CI=true yonatanaiz/client npm run test

after_success:
  - docker build -t yonatanaiz/server -f ./tasksapp/server/Dockerfile.dev ./tasksapp/server
  - docker build -t yonatanaiz/client -f ./tasksapp/front/Dockerfile.dev ./tasksapp/front
