export const types = {
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  LOADING: "LOADING",
  LOADING_DONE: "LOADING_DONE",

  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FALIURE: "LOGIN_FALIURE",

  SIGNUP: "SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FALIURE: "SIGNUP_FALIURE",

  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FALIURE: "GET_USER_FALIURE",

  IMAGE_UPLOAD: "IMAGE_UPLOAD",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  IMAGE_UPLOAD_FALIURE: "IMAGE_UPLOAD_FALIURE",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FALIURE: "LOGOUT_FALIURE",

  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FALIURE: "GET_USER_BY_ID_FALIURE",
};
