export const types = {
  SET_TASKS: "SET_TASKS",

  GET_TASKS: "GET_TASKS",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_FALIURE: "GET_TASKS_FALIURE",

  ADD_TASK: "ADD_TASK",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_FALIURE: "ADD_TASK_FALIURE",

  DELETE_TASK: "DELETE_TASK",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FALIURE: "DELETE_TASK_FALIURE",

  UPDATE_TASK: "UPDATE_TASK",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FALIURE: "UPDATE_TASK_FALIURE",

  ADD_SUB_TASK: "ADD_SUB_TASK",
  ADD_SUB_TASK_SUCCESS: "ADD_SUB_TASK_SUCCESS",
  ADD_SUB_TASK_FALIURE: "ADD_SUB_TASK_FALIURE",

  DELETE_SUB_TASK: "DELETE_SUB_TASK",
  DELETE_SUB_TASK_SUCCESS: "DELETE_SUB_TASK_SUCCESS",
  DELETE_SUB_TASK_FALIURE: "DELETE_SUB_TASK_FALIURE",

  UPDATE_SUB_TASK: "UPDATE_SUB_TASK",
  UPDATE_SUB_TASK_SUCCESS: "UPDATE_SUB_TASK_SUCCESS",
  UPDATE_SUB_TASK_FALIURE: "UPDATE_SUB_TASK_FALIURE",

  ADD_LOCATION_TO_TASK: "ADD_LOCATION_TO_TASK",
  ADD_LOCATION_TO_TASK_SUCCESS: "ADD_LOCATION_TO_TASK_SUCCESS",
  ADD_LOCATION_TO_TASK_FALIURE: "ADD_LOCATION_TO_TASK_FALIURE",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
};
